import Head from 'next/head';
import ModelRender from '../containers/model-render';

export default function Home() {
  return (
    <>
      <Head>
        <title>Travel into Italy</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main>
        <h1>THIS IS HOME</h1>
      </main>
    </>
  );
}
